name: project_structure
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  get_it: ^9.0.5
  injectable: ^2.6.0
  path_provider: ^2.1.5
  uuid: ^4.5.2
  flutter_svg: ^2.2.2
  bloc: ^9.1.0
  permission_handler: ^12.0.1
  intl: ^0.20.2
  connectivity_plus: ^7.0.0
  go_router: ^17.0.0
  freezed_annotation: any
  json_annotation: any
  json_serializable: any

  domain:
    path: './domain'

  core:
    path: './packages/core'

  shared:
    path: './packages/shared'

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^6.0.0
  build_runner: any
  injectable_generator: any
  freezed: any
  flutter_launcher_icons: ^0.14.4

flutter_gen:
  output: lib/core/asset_generator/
  line_length: 80

  integrations:
    image: true
    flutter_svg: true

  assets:
    enabled: true
    outputs:
      class_name: MyAssets
      style: camel-case

flutter:
  uses-material-design: true
  generate: true