name: project_structure
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  get_it: ^9.0.5
  injectable: ^2.6.0
  dio: ^5.9.0
  retrofit: ^4.9.0
  path_provider: ^2.1.5
  uuid: ^4.5.2
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.2
  bloc: ^9.1.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  permission_handler: ^12.0.1
  logger: ^2.6.2
  intl: ^0.20.2
  connectivity_plus: ^7.0.0
  go_router: ^17.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  json_serializable: ^6.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^6.0.0
  build_runner: ^2.10.1
  injectable_generator: ^2.9.1
  retrofit_generator: ^10.0.6
  freezed: ^3.2.3
  flutter_launcher_icons: ^0.14.4

flutter_gen:
  output: lib/.flutter_generator/
  line_length: 80

  integrations:
    image: true
    flutter_svg: true

  assets:
    enabled: true
    outputs:
      class_name: MyAssets
      style: camel-case

flutter:
  uses-material-design: true