name: core
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get_it: ^9.0.5
  injectable: ^2.6.0
  dio: ^5.9.0
  path_provider: ^2.1.5
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  json_serializable: ^6.11.1

  data:
    path: '../../data'

  project_structure:
    path: '../../'

  logger: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^6.0.0
  build_runner: ^2.10.1
  injectable_generator: ^2.9.1
  freezed: ^3.2.3

flutter:
